### ISSUE TITLE
Add users to database

### ISSUE THREAD

**Issue by ElliotThiebaut** [ElliotThiebaut/ettt-api#20]
Add a user collection that can manage all users in the database. A user should be linked by a user ID to the messages and have all the endpoints necessary to store and change information about a specific user.

**Comment by Floriansylvain** [comment]
I'll try to work on the routes on my side, you should create a "users" collection in the DB. Also, a user could have fields like username, e-mail and password. (in addition to the ID attributed by the DB) That would be a good start !

**Comment by ElliotThiebaut** [comment]
I'll work on the database structure as soon as I'm finished with the issue #22 !

**Comment by ElliotThiebaut** [comment]
It will also be important to clean the general chat collection in the database to replace every "username" filed in the documents with the user's ID

**Comment by ElliotThiebaut** [comment]
The User schema is available in the [docs](https://ettt-cloud.stoplight.io/docs/ettt-cloud-api/c2NoOjE4MjQwMTkx-user) under Schemas > User
