### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by ElliotThiebaut** [ElliotThiebaut/ettt-api#7]
To ensure that the database is protected and that only trusted user can write  to the database, an authentication system with tokens is necessery.

**Comment by killian-mahe** [comment]
There are many types of authentication flows (basic and bearer authentication, API keys, Oauth 2.0, etc.) The best one is the one that meets the needs of your API. So you need to be clear about the security requirements of your system. It is a ratio security / complexity.

**Comment by killian-mahe** [comment]
This article summarises three authentication flows that may be suitable for the project : https://zapier.com/engineering/apikey-oauth-jwt/
